title: My Guide
description: My personal guide book using the just-the-docs template!
theme: just-the-docs

url: https://stchiew.github.io/myguide/

aux_links:
  View GitHub Repository: https://github.com/stchiew/myguide

aux_links_new_tab: true
